# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
          {"python": "2.7", "toxenv": "py27-sdist"},
          {"python": "3.8", "toxenv": "py38-sdist"},
          {"python": "3.9", "toxenv": "py39-sdist"},
          {"python": "3.10", "toxenv": "py310-sdist"},
          {"python": "3.11", "toxenv": "py311-sdist,docs,formatting"}
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.version.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: test
      run: tox -e ${{ matrix.version.toxenv }}
